name: firebase_authentication
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  cloud_firestore: ^3.4.1
  firebase_core: ^1.20.0
  get: 4.6.5
  flutter: 
    sdk: flutter
  firebase_auth: ^3.5.1
  google_sign_in: ^5.4.0
  image_picker: ^0.8.5+3

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/images/